#version 460 core
#extension GL_NV_gpu_shader5 : require
#define SORTING_NETWORK_SIZE 256
layout(local_size_x = (SORTING_NETWORK_SIZE>>1), local_size_y = 1 , local_size_z = 1) in;

#moj_import <nvidium:occlusion/scene.glsl>
#moj_import <nvidium:sorting/sorting_network.glsl>



void populateSection(uint regionId, uint8_t sectionId) {
    ivec4 sectionHeader = sectionData[(regionId<<8)|uint(sectionId)].header;
    if (sectionEmpty(sectionHeader)) {
        putSortingData(sectionId, -999999999.0f); // empty section: push to back
    } else {
        ivec3 chunk = ivec3(sectionHeader.xyz)>>8;
        chunk.y &= 0x1ff;
        chunk.y <<= 32-9;
        chunk.y >>= 32-9;
        chunk -= chunkPosition.xyz;
        putSortingData(sectionId, abs(chunk.x) + abs(chunk.y) + abs(chunk.z));
    }
}

uint regionId = 0;

// No need to access the region header — section headers contain all required data
bool populate() {
    regionId = sortingRegionList[gl_WorkGroupID.x];
    populateSection(regionId, uint8_t(gl_LocalInvocationID.x<<1));
    populateSection(regionId, uint8_t((gl_LocalInvocationID.x<<1)|1));
    barrier();
    memoryBarrierShared();
    return false;
}

void updateSection(uint regionId, uint8_t id) {
    uint8_t from = id;
    uint8_t too = threadBufferIndex[id];
    ivec4 header = sectionData[(regionId<<8)|uint(from)].header;
    header.y &= ~(0xFF<<18);
    header.y |= int(uint(too))<<18;
    sectionData[(regionId<<8)|uint(from)].header = header;
}

void update() {
    updateSection(regionId, uint8_t(gl_LocalInvocationID.x<<1));
    updateSection(regionId, uint8_t((gl_LocalInvocationID.x<<1)|1));
}



void main() {
    if (populate()) {
        return;
    }

    // Bitonic sorting network over 256 elements (8 passes)
    //Net 0
    localSortA(0);
    //Net 1
    localSortA(1);
    localSortB(0);
    //Net 2
    localSortA(2);
    localSortB(1);
    localSortB(0);
    //Net 3
    localSortA(3);
    localSortB(2);
    localSortB(1);
    localSortB(0);
    //Net 4
    localSortA(4);
    localSortB(3);
    localSortB(2);
    localSortB(1);
    localSortB(0);
    //Net 5
    localSortA(5);
    localSortB(4);
    localSortB(3);
    localSortB(2);
    localSortB(1);
    localSortB(0);
    //Net 6
    localSortA(6);
    localSortB(5);
    localSortB(4);
    localSortB(3);
    localSortB(2);
    localSortB(1);
    localSortB(0);
    //Net 7
    localSortA(7);
    localSortB(6);
    localSortB(5);
    localSortB(4);
    localSortB(3);
    localSortB(2);
    localSortB(1);
    localSortB(0);

    update();
}